# Generated by Django 4.1.2 on 2023-03-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUploader1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('upload', models.FileField(upload_to='videos')),
            ],
        ),
        migrations.CreateModel(
            name='VideoUploader2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('upload', models.FileField(upload_to='videos')),
            ],
        ),
    ]
